
<../mkconfig

#all:V: $fluxsimulator $samtools $julia $star $cufflinks $bowtie $isolator \
#       $fastqdump $quip

all:V: cufflinks samtools star bowtie bowtie2 fastqdump quip isolator \
       bitseq rsem miso sailfish express

cufflinks:V: $cufflinks
samtools:V: $samtools
star:V: $star
fastqdump:V: $fastqdump
quip:V: $quip
isolator:V: $isolator
bitseq:V: $bitseq_parsealignment
bowtie:V: $bowtie
bowtie2:V: $bowtie2
rsem:V: $rsem_prepare_reference
miso:V: $miso
sailfish:V: $sailfish
salmon:V: $salmon
express:V: $express
kallisto:V: $kallisto
julia:V: $julia
rlsim:V: $rlsim
subsample:V: $subsample


#$mkfilepath/flux-simulator-%/bin/flux-simulator:
#    wget http://sammeth.net/artifactory/barna/barna/barna.simulator/$stem/flux-simulator-$stem.tgz
#    tar -xzf flux-simulator-$stem.tgz


$mkfiledir/flux-simulator-%/bin/flux-simulator:
    wget http://sammeth.net/artifactory/barna-nightly/barna/barna.simulator/$stem/flux-simulator-$stem.tgz
    tar xzf flux-simulator-$stem.tgz


$mkfiledir/samtools-%/samtools:
    wget -O samtools-$stem.tar.gz \
        https://github.com/samtools/samtools/archive/$stem.tar.gz
    tar -xzf samtools-$stem.tar.gz
    cd samtools-$stem
    make


$mkfiledir/julia/julia:
    git clone https://github.com/JuliaLang/julia.git
    git checkout release-0.3
    cd julia
    make
    julia -e 'Pkg.add("Distributions"); Pkg.add("DataFrames")'


$mkfiledir/STAR-STAR_%/source/STAR:
    wget https://github.com/alexdobin/STAR/archive/STAR_${stem}.tar.gz
    #wget http://it-collab01.cshl.edu/shares/gingeraslab/www-data/dobin/STAR/STARreleases/Patches/STAR_$stem.tgz
    tar -xzf STAR_${stem}.tar.gz
    cd STAR-STAR_$stem/source
    make POSIXSHARED
    #make


$mkfiledir/bowtie-%/bowtie:
    wget http://superb-dca3.dl.sourceforge.net/project/bowtie-bio/bowtie/$stem/bowtie-$stem-src.zip
    unzip bowtie-$stem-src.zip
    cd bowtie-$stem
    make


$mkfiledir/bowtie2-%/bowtie2:
    wget http://hivelocity.dl.sourceforge.net/project/bowtie-bio/bowtie2/$stem/bowtie2-${stem}-source.zip
    unzip bowtie2-$stem-source.zip
    cd bowtie2-$stem
    make


# Cufflinks requires boost
# On debian/ubuntu do: sudo apt-get install libboost-dev libboost-thread-dev
#                                           libboost-timer-dev libboost-system-dev
#                                           libhdf5-dev
$mkfiledir/cufflinks-%/src/cufflinks: $samtools
    wget http://cufflinks.cbcb.umd.edu/downloads/cufflinks-$stem.tar.gz
    tar xzf cufflinks-$stem.tar.gz
    cd cufflinks-$stem

    # seriously cufflinks?
    mkdir -p bam/lib bam/include/bam
    cp `dirname $samtools`/libbam.a bam/lib
    cp `dirname $samtools`/*.h bam/include/bam

    wget -O eigen-3.2.2.tar.bz2 http://bitbucket.org/eigen/eigen/get/3.2.2.tar.bz2
    tar xjf eigen-3.2.2.tar.bz2
    mkdir -p eigen/include
    mv eigen-eigen-1306d75b4a21/Eigen eigen/include

    ./configure --with-bam=`pwd`/bam --with-eigen=`pwd`/eigen
    make


$mkfiledir/rlsim/rlsim:
    git clone https://github.com/dcjones/rlsim.git
    cd rlsim
    make


$mkfiledir/isolator/build/src/isolator:
    git clone https://github.com/dcjones/isolator.git
    cd isolator/build
    cmake ..
    make


$mkfiledir/sra_sdk-2.3.5-2/linux/gcc/stat/x86_64/rel/bin/fastq-dump:
    wget http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.3.5-2/sra_sdk-2.3.5-2.tar.gz
    tar xzf sra_sdk-2.3.5-2.tar.gz
    cd sra_sdk-2.3.5-2
    make


$mkfiledir/quip-1.1.8/src/quip:
    wget http://homes.cs.washington.edu/~dcjones/quip/quip-1.1.8.tar.gz
    tar xzf quip-1.1.8.tar.gz
    cd quip-1.1.8
    ./configure
    make


$mkfiledir/BitSeq-%/parseAlignment:
    wget https://bitseq.googlecode.com/files/BitSeq-${stem}.tar.gz
    tar xzf BitSeq-${stem}.tar.gz
    cd BitSeq-${stem}
    make


$mkfiledir/rsem-%/rsem-prepare-reference:
    wget http://deweylab.biostat.wisc.edu/rsem/src/rsem-$stem.tar.gz
    tar xzf rsem-$stem.tar.gz
    cd rsem-$stem
    make


$mkfiledir/miso/miso:
    #wget http://pypi.python.org/packages/source/m/misopy/misopy-${stem}.tar.gz
    #tar xzf misopy-${stem}.tar.gz
    #cd misopy-${stem}
    virtualenv miso
    miso/bin/pip install misopy


# Needs:
#   libboost-iostreams-dev
#   libboost-filesystem-dev
#   libboost-system-dev
#   libboost-thread-dev
#   libboost-timer-dev
#   libboost-program-options-dev
#   libboost-program-options-dev
#   libboost-serialization-dev
#
#$mkfiledir/sailfish-%/build/src/sailfish:
#    wget -O sailfish-${stem}.tar.gz \
#        https://github.com/kingsfordgroup/sailfish/archive/v${stem}.tar.gz
#    tar xzf sailfish-${stem}.tar.gz
#    cd sailfish-${stem}
#
#    # having issues getting latest release to compile so I'm using git master
#    # git clone https://github.com/kingsfordgroup/sailfish.git
#    # cd sailfish
#
#    mkdir build
#    cd build
#    cmake -DFETCH_BOOST=TRUE ..
#    make

# Uugghh, I cannot build this shit. Let's just use binaries.

Sailfish-%-Linux_x86-64/bin/sailfish:
    wget https://github.com/kingsfordgroup/sailfish/releases/download/$stem/Sailfish-$stem-Linux_x86-64.tar.gz
    tar xzf Sailfish-$stem-Linux_x86-64.tar.gz


$mkfiledir/salmon/build/src/salmon:
    git clone https://github.com/COMBINE-lab/salmon.git
    cd salmon
    mkdir build
    cd build
    cmake -DFETCH_BOOST=TRUE ..
    make

#$mkfiledir/sailfish-%/build/src/salmon:
#    wget -O salmon-$stem.tar.gz https://github.com/kingsfordgroup/sailfish/archive/v$stem.tar.gz
#    tar xzf salmon-$stem.tar.gz
#    cd sailfish-$stem
#    mkdir build
#    cd build
#    cmake -DFETCH_BOOST=TRUE ..
#    make


$mkfiledir/express-%-src/build/src/express:
    wget http://bio.math.berkeley.edu/eXpress/downloads/express-${stem}/express-${stem}-src.tgz
    tar xzf express-${stem}-src.tgz
    cd express-${stem}-src

    git clone https://github.com/pezmaster31/bamtools.git
    mkdir -p bamtools/build
    cd bamtools/build
    cmake ..
    make

    cd ../..
    mkdir build
    cd build
    cmake ..
    make


$mkfiledir/kallisto/build/kallisto:
    git clone https://github.com/pachterlab/kallisto.git
    cd kallisto
    mkdir build
    cd build
    cmake ..
    make


$mkfiledir/subsample/subsample:
    git clone https://github.com/dcjones/subsample.git
    cd subsample
    make



