
<../../mkconfig


batch_effect_abundances= \
    ILM_AGR_A_1_2_1/abundances.cxb \
    ILM_BGI_A_1_2_1/abundances.cxb \
    ILM_CNL_A_1_2_1/abundances.cxb \
    ILM_MAY_A_1_2_1/abundances.cxb \
    ILM_NVS_A_1_2_1/abundances.cxb \
    ILM_AGR_A_2_2_1/abundances.cxb \
    ILM_BGI_A_2_2_1/abundances.cxb \
    ILM_CNL_A_2_2_1/abundances.cxb \
    ILM_MAY_A_2_2_1/abundances.cxb \
    ILM_NVS_A_2_2_1/abundances.cxb


all:V: batch_effect_isoforms.fpkm_table

%/abundances.cxb:X: ../%.bam
    $time -f "$TIMEFMT" -o $stem.time.log -- \
    $cuffquant \
        $human_genes \
        --num-threads 8 \
        --multi-read-correct \
        --output-dir $stem \
        $prereq 2> /dev/null
    # piping stderr to null since star will not write XS tags for junctions
    # without a defined strand, and cufflinks will whine and complain about
    # that.


batch_effect_genes.fpkm_table batch_effect_isoforms.fpkm_table: $batch_effect_abundances
    $cuffnorm \
        --num-threads 8 \
        --output-dir . \
        $human_genes \
        $prereq

    # Add an actually informative header

    mv genes.fpkm_table batch_effect_genes.fpkm_table.old
    echo -n gene_id > batch_effect_genes.fpkm_table
    for fn in $batch_effect_abundances; do
        printf "\t%s" `dirname $fn` >> batch_effect_genes.fpkm_table
    done
    echo >> batch_effect_genes.fpkm_table
    tail -n+2 batch_effect_genes.fpkm_table.old >> batch_effect_genes.fpkm_table
    rm batch_effect_genes.fpkm_table.old

    mv isoforms.fpkm_table batch_effect_isoforms.fpkm_table.old
    echo -n transcript_id > batch_effect_isoforms.fpkm_table
    for fn in $batch_effect_abundances; do
        printf "\t%s" `dirname $fn` >> batch_effect_isoforms.fpkm_table
    done
    echo >> batch_effect_isoforms.fpkm_table
    tail -n+2 batch_effect_isoforms.fpkm_table.old >> batch_effect_isoforms.fpkm_table
    rm batch_effect_isoforms.fpkm_table.old



