
<../../mkconfig

results=\
       1.1.1/abundance.tsv \
       1.1.2/abundance.tsv \
       1.1.3/abundance.tsv \
       1.2.1/abundance.tsv \
       1.2.2/abundance.tsv \
       1.2.3/abundance.tsv \

all:V: $results

kallisto_index: ../../data/Homo_sapiens.GRCh38.76.ERCC.fa
    $kallisto index -i kallisto_index ../../data/Homo_sapiens.GRCh38.76.ERCC.fa

%/abundance.tsv:X: kallisto_index
    $kallisto quant \
        --bias --threads 8 \
        -o $stem -i kallisto_index --plaintext \
        ../${stem}_end1.fq ../${stem}_end2.fq \

results:V: $results


transcript-expression.tsv:S$julia: $results
    using DataFrames

    joined = nothing
    for filename in split("$prereq")
        sample = symbol(match(r"^(\d+\.\d+\.\d+)\/", filename).captures[1])
        ex = readtable(filename, separator='\t', header=true)
        df = DataFrame(transcript_id=ex[:target_id])
        df[sample] = ex[:tpm]

        joined = joined == nothing ? df : join(joined, df, on=:transcript_id)
    end

    writetable("$target", joined, separator='\t')
