

<../../mkconfig

abundances= \
       1.1.1/results.xprs \
       1.1.2/results.xprs \
       1.1.3/results.xprs \
       1.2.1/results.xprs \
       1.2.2/results.xprs \
       1.2.3/results.xprs


all:V: $abundances

%.transcriptome.bam:X: ../%.transcriptome.bam
    $samtools sort -@ 8 -m 3G -n $prereq $stem.transcriptome

%/results.xprs:X: %.transcriptome.bam
    $time -f "$TIMEFMT" -o $stem.time.log -- \
    $express \
        -o $stem \
        ../../data/Homo_sapiens.GRCh38.76.ERCC.fa \
        $prereq


transcript-expression.tsv:S$julia: $abundances
    using DataFrames

    joined = nothing
    for filename in split("$prereq")
        sample = symbol(match(r"^(\d+\.\d+\.\d+)", filename).captures[1])
        ex = readtable(filename, separator='\t', header=true)
        df = DataFrame(transcript_id=ex[:target_id])
        df[sample] = ex[:tpm]

        joined = joined == nothing ? df : join(joined, df, on=:transcript_id)
    end

    writetable("$target", joined, separator='\t')
