
<../../mkconfig

isolator-output.h5: experiment.yml
    $isolator analyze --no-3p-correction $human_genes -o $target experiment.yml

#isolator-output.h5: experiment.yml
#    $isolator analyze $human_genes -o $target experiment.yml

gene-expression.tsv: isolator-output.h5
    $isolator summarize gene-expression $prereq

transcript-expression.tsv: isolator-output.h5
    $isolator summarize transcript-expression $prereq

condition-gene-expression.tsv: isolator-output.h5
    $isolator summarize condition-gene-expression $prereq

condition-transcript-expression.tsv: isolator-output.h5
    $isolator summarize condition-transcript-expression $prereq

differential-gene-expression.tsv: isolator-output.h5
    $isolator summarize differential-gene-expression $prereq

differential-transcript-expression.tsv: isolator-output.h5
    $isolator summarize differential-transcript-expression $prereq


batch-effect-isolator-output.h5: batch-effect-experiment.yml
    $isolator analyze \
        --no-frag-correction \
        $human_genes -o $target batch-effect-experiment.yml

batch-effect-transcript-expression.tsv: batch-effect-isolator-output.h5
    $isolator summarize transcript-expression -o $target $prereq


