
<../../mkconfig

thetaMeans=\
       1.1.1.thetaMeans \
       1.1.2.thetaMeans \
       1.1.3.thetaMeans \
       1.2.1.thetaMeans \
       1.2.2.thetaMeans \
       1.2.3.thetaMeans \

thetaMeans:V: $thetaMeans

%.prob:X: ../../data/Homo_sapiens.GRCh38.76.ERCC.fa ../%.transcriptome.ordered.bam
    $time -f "$TIMEFMT" -o $stem.parseAlignment.time.log -- \
    $bitseq_parsealignment \
        -f BAM \
        --procN 8 \
        -o $stem.prob \
        -s  ../../data/Homo_sapiens.GRCh38.76.ERCC.fa \
        -t $stem.tr \
        --verbose \
        ../$stem.transcriptome.ordered.bam


%.thetaMeans:X: %.prob
    $time -f "$TIMEFMT" -o $stem.estimateExpression.time.log -- \
    $bitseq_estimateexpression \
        --outType theta \
        -p parameters1.txt \
        -t $stem.tr \
        -o $stem \
        $stem.prob


transcript-expression.tsv:S$julia: $thetaMeans
    using DataFrames

    joined = nothing
    for filename in split("$thetaMeans")
        sample = replace(filename, ".thetaMeans", "")
        tbl = readtable(filename, separator=' ', header=false, allowcomments=true)
        tr = readtable(replace(filename, "thetaMeans", "tr"), separator=' ',
                       header=false, allowcomments=true)

        transcript_ids = tr[:x2]
        effective_length = tr[:x4]
        effective_length[effective_length .< 1000] = 1000
        transcript_expression = tbl[:x2] ./ effective_length

        df = DataFrame(transcript_id=transcript_ids)
        df[symbol(sample)] = transcript_expression

        if joined === nothing
            joined = df
        else
            joined = join(joined, df, on=:transcript_id)
        end
    end

    writetable("$target", joined, separator='\t')

