
<../../mkconfig

results=\
       ILM_BGI_A_1_1_1/quant.sf \
       ILM_BGI_A_2_1_1/quant.sf \
       ILM_BGI_A_3_1_1/quant.sf \
       ILM_BGI_A_4_1_1/quant.sf \
       ILM_BGI_A_5_1_1/quant.sf \
       ILM_BGI_B_1_1_1/quant.sf \
       ILM_BGI_B_2_1_1/quant.sf \
       ILM_BGI_B_3_1_1/quant.sf \
       ILM_BGI_B_4_1_1/quant.sf \
       ILM_BGI_B_5_1_1/quant.sf \
       ILM_BGI_C_1_1_1/quant.sf \
       ILM_BGI_C_2_1_1/quant.sf \
       ILM_BGI_C_3_1_1/quant.sf \
       ILM_BGI_C_4_1_1/quant.sf \
       ILM_BGI_C_5_1_1/quant.sf \
       ILM_BGI_D_1_1_1/quant.sf \
       ILM_BGI_D_2_1_1/quant.sf \
       ILM_BGI_D_3_1_1/quant.sf \
       ILM_BGI_D_4_1_1/quant.sf \
       ILM_BGI_D_5_1_1/quant.sf

all:V: $results


ref/transcriptome.klut: ../../data/Homo_sapiens.GRCh38.76.ERCC.fa
    $sailfish index -t $prereq -o ref -k 20


%/quant.sf:X: ref/transcriptome.klut
    mkfifo ${stem}_1.fastq
    $quip -cd ../${stem}_1.fastq.qp > ${stem}_1.fastq &
    mkfifo ${stem}_2.fastq
    $quip -cd ../${stem}_2.fastq.qp > ${stem}_2.fastq &

    $sailfish quant -i ref -l 'T=PE:O=><:S=U' \
        -1 ${stem}_1.fastq \
        -2 ${stem}_2.fastq \
        -o ${stem} --threads 8

    rm ${stem}_1.fastq ${stem}_2.fastq
